remote_theme: fongandrew/hydeout

title:   'Jonathan Chan'
url:     https://ionathanch.github.io

author:
  name: 'Jonathan Chan'
  url:  https://github.com/ionathanch

paginate: 6
paginate_path: /blog/page:num

sidebar_home_link: true
sidebar_blog_link: '/blog'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      comments: false
      
plugins:
  - jekyll-feed
  - jekyll-gist

# Custom variables
description: 'MSc. CS student @ UBC<br/><small><a href="http://pronoun.is/he/him">[he/him]</a></small>'
profile: assets/images/profile.jpg
social:
  github: https://github.com/ionathanch
  twitter: https://twitter.com/ionathanch
  keybase: https://keybase.io/ionathan
  orcid: https://orcid.org/0000-0003-0830-3180
