remote_theme: fongandrew/hydeout

title: 'Jonathan Chan'
url:   https://ionathan.ch/

author:
  name: 'Jonathan Chan'
  url:  https://github.com/ionathanch/

paginate: 8
paginate_path: /blog/page:num

sidebar_home_link: true
sidebar_blog_link: /blog/

defaults:
  - scope:
      type: posts
    values:
      comments: false
      excerpt_separator: "<!--more-->"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-katex

katex:
  js_path: _assets

# Custom variables
description: 'MSc. CS student @ UBC <br/>
  <small><a href="http://pronoun.is/he/him">[he/him]</a> ⦁
  <a href="https://cybre.space/tags/WaterDrinker">#WaterDrinker</a></small>'
profile: assets/images/profile.png
