remote_theme: fongandrew/hydeout

title:   ⟨ortho|normal⟩
url:     https://hilb.ert.space

author:
  name: 'Jonathan Chan'
  url:  https://github.com/ionathanch

paginate: 6

sidebar_home_link: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      comments: false
      
plugins:
  - jekyll-feed
  - jekyll-gist

# Custom variables
description: '{ not a blog about math }'
social:
  github: https://github.com/ionathanch
  twitter: https://twitter.com/ionathanch
  keybase: https://keybase.io/ionathan
